### PR TITLE
dex: bump dex container and set d2iq theme

### PR DESCRIPTION
**Pull request by mhrabovcin**
JIRA: https://jira.mesosphere.com/browse/DCOS-56832

Theme PR: https://github.com/mesosphere/dex/pull/2

### CODE REVIEW

**Comment by jongiddy** [comment]
@jaxesn Are you ok for this to happen now?

**Comment by jaxesn** [comment]
Let's hold. I think we might have a follow up PR and I want to verify with amr we can include the d2iq logo now.

**Comment by mhrabovcin** [comment]
@jaxesn FYI the logo is already in the public dex repo that is forked under `mesosphere` org.

**Comment by jaxesn** [comment]
I think once we merge this https://github.com/mesosphere/dex/pull/1, we will want another build then you can merge the tag change in this repo.

**Comment by mhrabovcin** [comment]
`config > frontend > issuer` should be changed to `D2iQ | Login` as part of this PR. See https://github.com/mesosphere/dex/pull/1#discussion_r306740299

**Comment by hectorj2f** [comment]
@mhrabovcin  what is the state of this PR ? It seems https://github.com/mesosphere/dex/pull/2 got merged

**Comment by shaneutt** [comment]
Double checking on this, should we be getting this is @mhrabovcin & @jaxesn ?

**Comment by jgehrcke** [comment]
@shaneutt I think we need to get this in. 

@mhrabovcin is already on vacation. @jongiddy WDYT?

**Comment by jgehrcke** [comment]
> I think once we merge this mesosphere/dex#1, we will want another build then you can merge the tag change in this repo.

That merged happened four days ago.

**Comment by jongiddy** [comment]
The merge was blocked because it reveals the new name. @jaxesn are we ready to proceed with this?

**Comment by jaxesn** [comment]
Can we merge https://github.com/mesosphere/dex/pull/5 and build a new dex container first?

**Comment by jaxesn** [comment]
@natmegs has merged the above PR in dex and rebuilt. This is now ready to merge.

**Pull request merged**
