### PR TITLE
enables ingress status update by Traefik

### PR DESCRIPTION
**Pull request by GoelDeepak**
Please see https://jira.mesosphere.com/browse/DCOS-55916 for detail

### CODE REVIEW

**Comment by shaneutt** [comment]
@GoelDeepak LGTM, but needs signed commits!

**Comment by GoelDeepak** [comment]
> TIL.
> If you still have a cluster please include an output example.

Its in the jira that I linked in this PR

**Comment by alejandroEsc** [comment]
@GoelDeepak you need to sign your PRs.

**Comment by jieyu** [comment]
This is a blocker for on-prem beta. So, please help merge this asap. Thanks!

**Comment by GoelDeepak** [comment]
> @GoelDeepak you need to sign your PRs.

@alejandroEsc @shaneutt I have signed the commit

**Comment by hectorj2f** [comment]
I merged as the comments has been addressed and due to the urgency of merging this PR.

**Pull request merged**
