### PR TITLE
kommander: be a chart

### PR DESCRIPTION
**Pull request by hectorj2f**
Move to use mesosphere/charts

### CODE REVIEW

**Comment by hectorj2f** [comment]
@DanielMSchmidt question: why would I need to install multiple instances of kommander in different namespaces in my cluster 🤔 ? You could pass the desired namespace when installing it via Helm, but in kubeaddons-configs we are setting the namespace to be `kommander`.

**Comment by DanielMSchmidt** [comment]
@hectorj2f The scenario we try to enable is to run one instance for Konvoy UI and one for the normal kommander usage. The other one would be if you need to split it up by organization

**Comment by hectorj2f** [comment]
@DanielMSchmidt :/, that increases the complexity based on how we install addons using helm 🤔. I will create a ticket to see how we can address this request. This PR aims to move kommander code to a chart based on the existing scripts

**Comment by DanielMSchmidt** [comment]
Sorry I think there was a misunderstanding.i would like to have the namespace configurable in the helm chart, but always install it with the same namespace in konvoy. I would like to be able to aim users towards an instantiation process for their second instance using helm and in this case it would be configurable. I understand this repo to be universal for helm installations, not bound to konvoy

**Comment by joejulian** [comment]
tiller will create a namespace when you helm install to a namespace, ie:
"helm install --namespace fubar stable/minecraft" will create the
namespace "fubar" if it does not exist. We should not put namespace
records in helm charts, nor should we add namespace to the metadata. We should use the helm's namespace management directly.

**Comment by joejulian** [comment]
"an instantiation process for their second instance" would look like:
```
helm install --namespace my_kommander mesospher_stable/kommander
```

**Comment by DanielMSchmidt** [comment]
Ah, so the namespace option in helm sets every namespace in the kubernetes objects to be that namespace? That sounds awesome, I wish they had the feature back when I was working with it :D (or they had and we didn't know)

**Comment by hectorj2f** [comment]
@DanielMSchmidt that depends on the year you were working with it :)

**Pull request merged**
