### PR TITLE
konvoy-ui: don't attempt to create the CRD

### PR DESCRIPTION
**Pull request by hectorj2f**
related to: https://github.com/mesosphere/charts/pull/53

### CODE REVIEW

**Comment by s12chung** [comment]
please move `konvoy-ui` to install after `kommander`, they're running in parallel: https://github.com/mesosphere/kubeaddons/blob/c6333b85d81a0eefe5a84444bd6fff93f99263e0/pkg/workflows/dependent_workflow.go#L36

**Comment by s12chung** [comment]
otherwise, lgtm.

**Comment by hectorj2f** [comment]
@s12chung what is the problem of installing them in parallel ? Please explain it to me

**Comment by s12chung** [comment]
`op-portal` will try to create an instance of that CRD, so in a way, it's dependent on `kommander`. so they shouldn't be in parallel.

**Comment by hectorj2f** [comment]
no, it is done here https://github.com/mesosphere/kubeaddons/pull/317

**Pull request merged**
