### PR TITLE
Add Velero

### PR DESCRIPTION
**Pull request by shaneutt**
This PR adds Velero to the manifest based addons.

### CODE REVIEW

**Comment by s12chung** [comment]
i'm not sure if we should move away from helm for this....? just to make it work for the new kubeaddons.

**Comment by shaneutt** [comment]
@s12chung part of the intent here was to package minio and velero together into a single Addon, given what's provided in the velero repository as the helm chart doesn't provide options to deploy minio alongside it (though velero provides an example minio setup which we're now using).

**Comment by joejulian** [comment]
I feel charts are the units we should be focused on supporting. This tech debt we're banking for charts that don't do what we need should be fixed by working upstream on improving our adding charts.

We could fix Velero by adding Minio as a subchart and installing them both together.

**Comment by shaneutt** [comment]
> We are loosing all the benefits of using helm values yaml definitions cry. Why don't we deploy both together via kubeaddons as done for elasticsearch + elasticsearchexporter ?

I'm not confident in the benefits of using helm charts vs. manifest based implementations @hectorj2f. I personally feel like this way of packaging Velero provides a bit more clarity about components, at the cost of some verbosity.

> I'd suggest to have a separate template for minio.

A separate addon?

> This is a nightmare to maintain YAML in YAML.

This is a problem we already had, and we have it whether we use manifests or helm values. We need to solve this problem, but I would contend that this PR is not the place to do so, and simply having _less_ yaml in yaml by using helm charts is not significantly helpful I think.

Let me know your thoughts.

**Comment by shaneutt** [comment]
@hectorj2f & @joejulian upstream chart improvements, subcharts, and other things sound nice, and I'm not opposed, but could we agree that this is a separate concern from what's trying to be accomplished here and would it be a fair compromise to look at this problem more wholesale later (as per a JIRA that we can spin up as a follow up to this)? It seems like we're currently discussing on unspoken rules, I think having a conversation and follow up that leads to actual rules would be more appropriate, let me know your thoughts.

**Comment by shaneutt** [comment]
Closing this, will revisit later

**Comment by hectorj2f** [comment]
@shaneutt What did it change since my latest review ?

**Comment by hectorj2f** [comment]
I thought we were having a pending discussion about this PR, but it seems we don't have it.

**Comment by shaneutt** [comment]
To continue discussion on this, the changes were pulled and https://github.com/mesosphere/kubeaddons-configs/pull/31 has been created as a follow up.

**Pull request merged**
