### PR TITLE
templates: bump 'localvolumeprovisioner'

### PR DESCRIPTION
**Pull request by nfnt**
Version 0.5.0 of 'localvolumeprovisioner' adds support for multiple
storage classes.

### CODE REVIEW

**Comment by shaneutt** [comment]
@nfnt I understand you're on vacay this week, we're going to temporarily close this since there's no action that can be taken right now and catch up with you next week, I've set a reminder on slack I'll check in with you monday and we'll get this ball rolling again :+1:

**Comment by shaneutt** [comment]
Ok, re-opening this as nfnt is back and we checked in this morning that everything should be good to go :+1:

**Comment by nfnt** [comment]
Closed in favor of https://github.com/mesosphere/kubeaddons-configs/pull/193.

**Comment by nfnt** [comment]
Reopened, as the decision was made to use this approach instead of the one in #193. Needs https://github.com/mesosphere/charts/pull/115 to be merged first.

**Comment by shaneutt** [comment]
This is now blocked on https://github.com/mesosphere/charts/pull/115

**Pull request merged**
