### PR TITLE
Update all addon-init references

### PR DESCRIPTION
**Pull request by jr0d**
# Testing

Binaries built with a 1.13.1 docker image. I am requesting access so that I can create a tag under the mesosphere docker org.

### CODE REVIEW

**Comment by jr0d** [comment]
@hectorj2f This is just for testing, I will create a new docker image tag under the mesosphere project once CI passes and I have access.

**Comment by hectorj2f** [comment]
@jr0d Alright!

**Comment by shaneutt** [comment]
@jr0d just checking in: need any help with anything here? everything going good?

**Comment by jr0d** [comment]
closing stale PR

**Pull request closed without merging**
