### PR TITLE
Add metrics-server addon

### PR DESCRIPTION
**Pull request by dkoshkin**
This enables HPA and `kubectl top` and dashboards in the kubernetes-dashboard.

### CODE REVIEW

**Comment by jieyu** [comment]
Can we hold-off on this PR? I feel it's a bit redundant with the current monitoring pipeline (based on Prometheus). I just don't know if this is gonna introduce tech debt or not. I need to do more research on this.

**Comment by dkoshkin** [comment]
Yep lets talk about it.

**Comment by hectorj2f** [comment]
@dkoshkin @jieyu I did some research already and it is common to have the metrics-server and prometheus running together to extract additional metrics. That is the benefit of running the metrics server alongside with Prometheus.

However, I found this adapter which replaces the necessity of the metrics-server https://github.com/DirectXMan12/k8s-prometheus-adapter. WDYT ?

**Comment by hectorj2f** [comment]
This adapter can be installed as helm chart https://github.com/DirectXMan12/k8s-prometheus-adapter. It is relevant to have the additional metrics that the metrics-server or adapter collect because those would help us with the performance workload test.

**Comment by shaneutt** [comment]
Marked this as paused because it seems there are some additional considerations in the comments to go over before this is fully ready for review.

**Comment by jieyu** [comment]
@hectorj2f I prefer `k8s-prometheus-adapter`

**Comment by jieyu** [comment]
I am wondering what metrics are not yet in the metrics pipeline that metrics server provides?

**Comment by hectorj2f** [comment]
as said metrics-server is used in other components, but let's give a try to the k8s-prometheus-adapter.

@jieyu mentioned that it is maintained by Google people

**Comment by shaneutt** [comment]
Since we seem to be going with another implementation for the moment, seems like we should close this for now and we can re-open this if we need to revisit.

**Pull request closed without merging**
