### PR TITLE
[DCOS-59630] repository name and labels and mechanism for tags

### PR DESCRIPTION
**Pull request by alejandroEsc**
This PR provides:

Repository name and ref labels for all addons. 

It also includes a mechanism for creating new tags and pushing them when we wish to update the refs and create a new tag to be used by konvoy. For now this is a manual process with the hopes of creating an automated process in the future.  

sample run:
```
$ GIT_TAG=alejandro make tag.create
updating addons with tag: alejandro
[ae/kubeaddonsversions 92c8767] changed ref labels to alejandro
 26 files changed, 26 insertions(+), 26 deletions(-)
HEAD is now at 76dd106 makefile updated
```
then we should push the tag:

```
$ GIT_TAG=alejandro make tag.push
echo "pushing tag: alejandro"
pushing tag: alejandro
git push origin alejandro
Enumerating objects: 56, done.
Counting objects: 100% (56/56), done.
Delta compression using up to 12 threads
Compressing objects: 100% (30/30), done.
Writing objects: 100% (30/30), 3.39 KiB | 3.39 MiB/s, done.
Total 30 (delta 27), reused 0 (delta 0)
remote: Resolving deltas: 100% (27/27), completed with 25 local objects.
To github.com:mesosphere/kubeaddons-configs.git
 * [new tag]         alejandro -> alejandro
```

at this point the tag `alejandro` exists and has the right ref as expected

### CODE REVIEW

**Comment by hectorj2f** [comment]
Cannot we set these labels during the creation ? I prefer it than rather maintaining python code and hardcoded values

**Comment by hectorj2f** [comment]
Cannot we use a mutating webhook to set them?

**Comment by hectorj2f** [comment]
Perhaps Konvoy or the clients should be in charge of setting these labels during creation. I initially thought about the webhook but we still need to identify the repo owner.

**Comment by alejandroEsc** [comment]
Discussed this off channel with @joejulian and @samba it was a bit unclear what the goal was and so i opened the discussion on slack. The conclusion is an approach that is more dynamic, and so that is what we shall do. Closing this PR.

**Pull request closed without merging**
